### ISSUE TITLE
Revise aget calls

### ISSUE THREAD

**Issue by mfikes** [forward-blockchain/qlkit#5]
Consider using [`:checked-arrays :warn`](https://clojurescript.org/reference/compiler-options#checked-arrays) to catch calls to `aget` with string indices. More info is at [Checked Array Access](https://clojurescript.org/news/2017-07-14-checked-array-access).

Here is one example that could be revised:

https://github.com/forward-blockchain/qlkit/blob/af4adfc2afebd208662282ce014abc05bcd8f838/src/qlkit/core.cljc#L228

**Comment by craig-ludington** [comment]
commit dc25fc6

Thanks, good article!
